config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams do
    member do
      get 'add_member:id', :action => 'add_member', :as => 'add_member'
      get 'invite/:id', :action => 'invite', :as => 'invite'
    end
  end

  resources :stories 
    resources :tags do
      member do
        get 'new/:id', :action => 'new', :as => 'new'
        post 'create/:id', :action => 'create', :as => 'create'
      end
  end

  devise_for :users, :controllers => {registration: "registrations", sessions: "sessions", invitations: 'invitations'}
   #root to: 'home#index'
  
  devise_scope :user do
    root to: 'users#index'
    get 'profile' => "users#profile"
  end

   resources :users do
    member do
      get 'profile'
    end
  end

  resources :sites do
    get 'settings' => "sites#settings"
    get 'home' => "sites#home"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories

  has_many :members
  has_many :teams, through: :members

  mount_uploader :avatar, AvatarUploader

  enum role: [ :author, :admin, :editor ]

  def self.generate_slug(user)
    split = user.full_name.split(" ")
    first_name = split[0]
    last_name = split[1]
    x = first_name + "-" + last_name.slice!(0, 1)
    user.update(slug: x)
  end

  after_create :set_admin

  private

    def set_admin
      users = User.all
      if users.count == 1
        self.admin!
        user.update
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :profile]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def profile
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        User.generate_slug(@user) 
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :bio, :slug, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label :avatar %>
    <% if current_user.admin? %>
      <% if @user.avatar? %>
        <%= image_tag(@user.avatar_url.to_s) %>
      <% else %>
        <%= image_tag("avatar.png", size: "50x50", alt: "Image") %>
        <%= puts 'Avatar' %>
    <% end %>
    <% else %>
      <% if @user.avatar? %>
        <%= image_tag(@user.avatar_url.to_s) %>
        <%= form.file_field :avatar, id: :user_avatar %>
      <% else %>
        <%= image_tag("avatar.png", size: "50x50", alt: "Image") %>
        <%= form.file_field :avatar, id: :user_avatar %>
      <% end %>
    <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <% if current_user.admin? %>
      <%= form.text_field :full_name, id: :user_full_name, :readonly => true %>
    <% else %>
      <%= form.text_field :full_name, id: :user_full_name %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <% if current_user.admin? %>
      <%= form.text_field :email, id: :user_email, :readonly => true %>
    <% else %>
      <%= form.text_field :email, id: :user_email %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <% if current_user.admin? %>
      <%= @user.encrypted_password %>
    <% else %>
      <%= link_to 'Change password' %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <% if current_user.admin? %>
      <%= form.text_field :role, id: :user_role %>
    <% else %>
      <%= form.text_field :role, id: :user_role, :readonly => true  %>
    <% end %>
  </div>


  <div class="field">
    <%= form.label :bio %>
    <% if current_user.admin? %>
      <%= form.text_area :bio, id: :user_bio, :readonly => true  %>
    <% else %>
      <%= form.text_area :bio, id: :user_bio %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.button 'Save',
      type: :submit,
      data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..." } 
    %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', profile_user_path(@user) %>

app/views/users/index.html.erb
<h1>Blog</h1>

<% if current_user %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Log in', new_user_session_path %>
<% end %>
  <%= link_to 'Stories', stories_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<h1>Profile for <%= @user.full_name %></h1>

<div class="container">

<div class="row">

<div class="col-md-6">

<p>
  <strong>Image:</strong>

  <div class="hovereffect">
    <div class="img-responsive">
      <% if @user.avatar? %>
      <%= image_tag(@user.avatar_url.to_s) %>
      <% else %>
      <%= image_tag("avatar.png", size: "50x50")%>
      <% end %>
    </div>
    <div class="overlay">
      <p><%= file_field :avatar, id: :user_avatar, :title => "Upload New" %></p> 
    </div>
  </div>
</p>

</div>

<div class="col-md-6">

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @user.slug %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.encrypted_password %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', teams_path %>

</div>

</div>
</div>

app/views/users/show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag(@user.avatar.to_s) if @user.avatar? %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @user.slug %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', teams_path %>