config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams do
    member do
      get 'add_member:id', :action => 'add_member', :as => 'add_member'
      get 'invite/:id', :action => 'invite', :as => 'invite'
    end
  end

  resources :stories 
    resources :tags do
      member do
        get 'new/:id', :action => 'new', :as => 'new'
        post 'create/:id', :action => 'create', :as => 'create'
      end
  end

  devise_for :users, :controllers => {registration: "registrations", sessions: "sessions", invitations: 'invitations'}
   #root to: 'home#index'
  
  devise_scope :user do
    root to: 'users#index'
    get 'profile' => "users#profile"
  end

   resources :users do
    member do
      get 'profile'
    end
  end

  resources :sites do
    get 'settings' => "sites#settings"
    get 'home' => "sites#home"
  end

end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user, required: false
  has_many :tags

  def author
  	user = User.find(author_id)
  end

	def self.search(search)
	  if search
	    Story.where("title LIKE ?", "%#{search}%")
	  else
	    Story.all
	  end
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.search(params[:search])
    @tags = Tag.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])
  end

  # GET /stories/new 
  def new
    @story = Story.new
    authorize @story
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.author_id = current_user.id
    authorize @story

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :part, :author_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :story_title %>
  </div>

  <div class="field">
    <%= form.label :part %>
    <%= form.text_area :part, id: :story_part %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Stories</h1>

<%= form_tag stories_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Part</th>
          <th>Author</th>
          <th colspan="2">Tags</th>

          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @stories.each do |story| %>
          <tr>

            <td><%= story.title %></td>
            <td><%= story.part %></td>
            <td><%= story.author.full_name %></td>
      
            <% Tag.count? %>

              <% story.tags.each do |t| %>
                  <td><%= t.name %></td>
              <% end %>

            <% if current_user %>

              <td><%= link_to 'Add tags', new_tag_path(story) %></td>
              <td><%= link_to 'Show', story %></td>
              <td><%= link_to 'Edit', edit_story_path(story) %></td>

              <% if current_user.admin? %>
                <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>

            <% end %>
          </tr>
         
        <% end %>
      </tbody>
    </table>

  </p>
<% end %>

<br>

<% if current_user %>
  <%= link_to 'Team', teams_path %>
  <%= link_to 'New Story', new_story_path %>
  <%= link_to 'Your profile', profile_user_path(current_user) %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

  <%= link_to 'Create site', new_site_path %>
  <%= link_to 'View sites', sites_path %>
<% else %>
  <%= link_to 'Back', root_path %>
<% end %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Part:</strong>
  <%= @story.part %>
</p>

<p>
  <strong>Author:</strong>
  <%= @story.author %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @story.tags %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>