config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams do
    member do
      get 'add_member:id', :action => 'add_member', :as => 'add_member'
      get 'invite/:id', :action => 'invite', :as => 'invite'
    end
  end

  resources :stories 
    resources :tags do
      member do
        get 'new/:id', :action => 'new', :as => 'new'
        post 'create/:id', :action => 'create', :as => 'create'
      end
  end

  devise_for :users, :controllers => {registration: "registrations", sessions: "sessions", invitations: 'invitations'}
   #root to: 'home#index'
  
  devise_scope :user do
    root to: 'users#index'
    get 'profile' => "users#profile"
  end

   resources :users do
    member do
      get 'profile'
    end
  end

  resources :sites do
    get 'settings' => "sites#settings"
    get 'home' => "sites#home"
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :story, required: false

  def self.count?
  	if Tag.count != 0
  	end
  end

  def self.story(sid)
  	story_id = sid
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def new
	 @tag = Tag.new
	 @story = Story.find(params[:id])
	 @tag.story_id = @story.id
	end

	def create 
		@tag = Tag.new(tag_params)
	 	@story = Story.find(params[:id])
    @tag.story_id = @story.id

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }

      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
	end

	def show 
		@tag = Tag.find(params[:id])
	end

	private
    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
  <%= form_for @tag , :url => create_tag_path(@story), html:{method:'post'} do |f| %>
    <p>Name:
      <%= f.text_area :name %>
    </p>
    
    <p>
      <%= f.submit %>
    </p>
    <% end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render partial: 'form', tag: @tag %>

<%= link_to 'Back', stories_path %>

app/views/tags/show.html.erb
<p>
  <strong>Tag name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Tag for story:</strong>
  <%= @tag.story_id %>
</p>

<%= link_to 'Back', stories_path %>