config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :teams do
    member do
      get 'add_member:id', :action => 'add_member', :as => 'add_member'
      get 'invite/:id', :action => 'invite', :as => 'invite'
    end
  end

  resources :stories 
    resources :tags do
      member do
        get 'new/:id', :action => 'new', :as => 'new'
        post 'create/:id', :action => 'create', :as => 'create'
      end
  end

  devise_for :users, :controllers => {registration: "registrations", sessions: "sessions", invitations: 'invitations'}
   #root to: 'home#index'
  
  devise_scope :user do
    root to: 'users#index'
    get 'profile' => "users#profile"
  end

   resources :users do
    member do
      get 'profile'
    end
  end

  resources :sites do
    get 'settings' => "sites#settings"
    get 'home' => "sites#home"
  end

end

app/models/site.rb
class Site < ApplicationRecord
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
	before_action :set_site, only: [:show, :edit, :update, :destroy]

	def index
		@sites = Site.all
	end

  def show
    @stories = Story.all
  end

	def edit
		@site = Site.find(params[:id])
	end

	def update
		respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

	def new
		@site = Site.new
	end

	def create
		@site = Site.new(site_params)

		respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end	
  end

	private

	def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :theme)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_with(model: site, local: true) do |form| %>
  
  <div class="field">
   <p>The name of your site: </p>
    <%= form.text_field :name, id: :site_name %>
  </div>

  <div class="field">
    <p>Used in your theme, meta data and search results: </p>
    <%= form.text_area :theme, id: :site_theme %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Title and description</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', stories_path %>

app/views/sites/index.html.erb
<h1>All sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Theme</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |s| %>
      <tr>

        <td><%= s.name %></td>
        <td><%= s.theme %></td>

        <td><%= link_to 'View site', site_path(s) %></td>
        <td><%= link_to 'General settings', edit_site_path(s) %></td>

      </tr>
     
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', stories_path %>

app/views/sites/new.html.erb
<h1>Title and description</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', stories_path %>

app/views/sites/settings.html.erb
<h1>Title and description</h1>

<%= render 'form', site: @site %>


<%= link_to 'Show', @site %> |
<%= link_to 'Back', stories_path %>

app/views/sites/show.html.erb
<h1>Title and description</h1>

<p>
  <strong>The name of your site:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Used in your theme, meta data and search results:</strong>
  <%= @site.theme %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> 
<%= link_to 'Back', sites_path %>


<h2>Stories</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Part</th>
      <th>Author</th>
      <th colspan="2">Tags</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>

        <td><%= story.title %></td>
        <td><%= story.part %></td>
        <td><%= story.author.full_name %></td>
  
          <% story.tags.each do |t| %>
              <td><%= t.name %></td>
          <% end %>
        <td><%= link_to 'View story', story %></td>

      </tr>
     
    <% end %>
  </tbody>
</table>